[package]
name = "afl-icicle-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
bstr = { version = "1.3.0", default-features = false }
icicle-vm = { path = "../icicle-vm" }
icicle-fuzzing = { path = "../icicle-fuzzing" }
icicle-gdb = { path = "../icicle-gdb" }
libc = "0.2.140"
serde_json = "1.0.94"
target-lexicon = "0.12.6"
tracing = { version = "0.1.37", default-features = false, features = ["release_max_level_trace"] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["fmt", "env-filter", "ansi"] }
pcode = { path = "../sleigh/pcode" }
