[package]
name = "icicle-fuzzing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
icicle-vm = { path = "../icicle-vm" }
pcode = { path = "../sleigh/pcode" }
sleigh-runtime = { path = "../sleigh/sleigh-runtime" }
target-lexicon = "0.12.6"
tracing = { version = "0.1.37", default-features = false }
serde = { version = "1.0.155", features = ["derive"] }
ron = "0.8.0"
bitflags = "1.3.2"
bytemuck = { version = "1.13.1", features = ["derive"] }
ihex = "3.0.0"
crepe = "0.1.7"
indexmap = "1.9.2"
hashbrown = "0.13.2"
