[package]
name = "icicle-fuzzing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.60"
icicle-vm = { path = "../icicle-vm" }
pcode = { path = "../sleigh/pcode" }
sleigh-runtime = { path = "../sleigh/sleigh-runtime" }
target-lexicon = "0.12.4"
tracing = { version = "0.1.36", default-features = false }
serde = { version = "1.0.142", features = ["derive"] }
ron = "0.7.1"
bitflags = "1.3.2"
bytemuck = { version = "1.11.0", features = ["derive"] }
ihex = "3.0.0"
crepe = "0.1.6"
