[package]
name = "icicle-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
addr2line = "0.18.0"
bitflags = "1.3.2"
icicle-mem = { path = "../icicle-mem" }
pcode = { path = "../sleigh/pcode" }
sleigh-runtime = { path = "../sleigh/sleigh-runtime" }
target-lexicon = "0.12.4"
tracing = { version = "0.1.36", default-features = false }
object = { version = "0.29.0", default-features = false, features = ["read_core", "elf"] }
bytemuck = "1.11.0"

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }
