[package]
name = "icicle-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
addr2line = "0.19.0"
bitflags = "1.3.2"
icicle-mem = { path = "../icicle-mem" }
pcode = { path = "../sleigh/pcode" }
sleigh-runtime = { path = "../sleigh/sleigh-runtime" }
target-lexicon = "0.12.6"
tracing = { version = "0.1.37", default-features = false }
object = { version = "0.30.3", default-features = false, features = ["read_core", "elf"] }
bytemuck = "1.13.1"
hashbrown = "0.13.2"

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }
