[package]
name = "icicle-gdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
gdbstub = "0.6.4"
gdbstub_arch = "0.2.4"
icicle-vm = { path = "../icicle-vm" }
num-traits = "0.2.15"
pcode = { path = "../sleigh/pcode" }
target-lexicon = "0.12.6"
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["fmt", "tracing-log", "env-filter", "ansi"] }
